#!/bin/bash

set -e
cd dist;

echo -e "\033[33;1m    -> Start RMI registry \033[0m"
( for dir in `pwd`; do /usr/lib/jvm/java-8-oracle/bin/rmiregistry 14331 -Djava.rmi.server.codebase=file://$dir/ ; done) &

sleep 2
echo "AAA" $0
echo "TEST => " $2

for (( i=1; i<=$2; i++ ))
do

    echo -e "\033[33;1m    -> Start server $i of $1 \033[0m"
    ( for dir in `pwd`; do export LD_LIBRARY_PATH=$dir ;  /usr/lib/jvm/java-8-oracle/bin/java -cp . -Djava.security.policy=$dir/java.policy -Djava.rmi.server.codebase=file://$dir/ Server $i; done ) &

    sleep 2

done

echo -e "\033[33;1m\n\n    -> Start client \033[0m\n"
/usr/lib/jvm/java-8-oracle/bin/java -Djava.security.policy=java.policy Client taurus $2 $1

echo -e "\033[33;1m\n\n\n    -> Closing java servers and RMI\033[0m \033[30;1m"
kill $(pidof java)
kill $(pidof rmiregistry)

sleep 1
